
pipeline 
{
    agent
    {
        label 'master'
    }

    stages 
    {
        stage('Debug-ploop')
        {
            steps
            {
                echo "debug: 1"
                echo "inventory path: ${ansible_inventory_path}"
            }
        }

        stage('Build') 
        {
            steps 
            {
                echo 'Building...'

                sh '''
                    pwd

                    ls -ltrh

                    cd neje-engrave/src/main/ansible

                    cp ${ansible_inventory_path} .

                    ls -ltrh

                    ls -ltrh hosts/
                '''


/*
                    ansible-playbook -vvvv consul.yml -i hosts/service-discovery --extra-vars "ansible_become_pass=${mirror_password} ansible_sudo_pass=${mirror_password}"
*/
            }
        }
    }
}
