
pipeline 
{
    agent
    {
        label 'master'
    }

    stages 
    {
        stage('Debug-ploop')
        {
            steps
            {
                echo "debug: 1"
                echo "inventory path: ${ansible_inventory_path}"
            }
        }

        stage('Build') 
        {
            steps 
            {
                echo 'Building...'

                sh 
                '''    
                    pwd

                    ls -ltrh
                '''


/*
                    ls -la

                    svn checko1ut https://192.168.1.80/beto-land-owner/Websites/oneweb/beto-land-network/src/main/configuration-mangement-ansible/jdsfkdsafjsajfkjaldsj

                    ls -la

                    cd configuration-mangement-ansible

                    ls -la

                    ansible-playbook -vvvv consul.yml -i hosts/service-discovery --extra-vars "ansible_become_pass=${mirror_password} ansible_sudo_pass=${mirror_password}"
*/
            }
        }
    }
}
