
pipeline 
{
    agent
    {
        label 'master'
    }

    stages 
    {
        stage('Deploy') 
        {
            steps 
            {
                echo 'Deploying...'

                sh '''
                    pwd

                    ls -ltrh

                    cd neje-engrave/src/main/ansible

                    cp ${ansible_inventory_path} .

                    ls -ltrh

                    ansible-playbook deploy-war.yml -i ansible-betoland.inventory -l laserengraver1
                '''
            }
        }
    }
}
